import java.io.*;
import java.beans.*;
import java.net.*;
import java.util.*;
import java.awt.event.*;

public class PluginManager extends javax.swing.JFrame implements ActionListener {
    Vector pluginList;
    Vector buttonList;
    public static File pluginsdir = new File(System.getProperty("user.dir")+System.getProperty("file.separator")+"plugins");

    public PluginManager() {
        pluginList = new Vector();
        buttonList = new Vector();
        try { pluginList = getPlugins(); } 
        catch (Exception e) { System.err.println("Couldn't load all the plugins: "+e); }
        
        initComponents();
    }
    
    public PluginManager(ClntComm parent) {
        pluginList = parent.getPlugins();
        buttonList = new Vector();
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        iconsPanel = new javax.swing.JPanel();
        iconScrollPane = new javax.swing.JScrollPane();
        iconListPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Plugin Settings");
        setName("pluginFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        iconListPanel.setLayout(new javax.swing.BoxLayout(iconListPanel, javax.swing.BoxLayout.Y_AXIS));

        loadIcons();
        iconScrollPane.setViewportView(iconListPanel);

        iconsPanel.add(iconScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(iconsPanel, gridBagConstraints);

        settingsPanel.setLayout(new java.awt.GridLayout(1, 0));

        loadSettingsPanel(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(settingsPanel, gridBagConstraints);

        pack();
    }//GEN-END:initComponents
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      setVisible(false);
      dispose();
  }//GEN-LAST:event_exitForm
  
  private void loadSettingsPanel(int index) {
      try{
          Object bean = pluginList.elementAt(index);
          BeanInfo pluginInfo = Introspector.getBeanInfo(bean.getClass());
          Class customizerClass = pluginInfo.getBeanDescriptor().getCustomizerClass();
          Customizer customizer = (Customizer)customizerClass.newInstance();
          customizer.setObject(bean);
          settingsPanel.removeAll();
          settingsPanel.add((javax.swing.JPanel)customizer);
          settingsPanel.validate();
      } catch(Exception e) {
          System.err.println("Couldn't load settings: "+e);
          e.printStackTrace(System.out);
      }
  }
  
  private void loadIcons() {
      try{
          for(int i=0; i<pluginList.size(); i++) {
              BeanInfo pluginInfo = Introspector.getBeanInfo(pluginList.elementAt(i).getClass());
              javax.swing.JButton button = new javax.swing.JButton();
              java.awt.Image icon = pluginInfo.getIcon(SimpleBeanInfo.ICON_COLOR_32x32);
              button.setIcon(new javax.swing.ImageIcon(icon));
              iconListPanel.add(button);
              buttonList.add(button);
              button.addActionListener(this);
          }
      } catch(IntrospectionException e) {
          System.err.println("Couldn't load icons: "+e);
      }
  }
  
  public static Vector getPlugins() throws MalformedURLException, ClassNotFoundException, IOException {
      File prefsdir = new File(System.getProperty("user.home")+System.getProperty("file.separator")+"CsltComm");

      System.out.println("Looking for plugins in "+pluginsdir);
      File[] pluginfiles = pluginsdir.listFiles(new FilenameFilter() {
          public boolean accept(File dir, String name) {
              return name.endsWith(".jar");
          }
      });
      
      URL[] pluginurls = new URL[pluginfiles.length];
      for(int i=0; i<pluginfiles.length; i++)
          pluginurls[i] = pluginfiles[i].toURL();
      
      ClassLoader loader = new URLClassLoader(pluginurls);
      Thread.currentThread().setContextClassLoader(loader);  //Sun BugID 4676532
      
      Vector pluginList = new Vector(pluginfiles.length);
      for(int i=0; i<pluginfiles.length; i++) {
          String currBean = pluginfiles[i].getName();
          currBean = currBean.substring(0, currBean.lastIndexOf(".jar"));
          
          File serializedFile = new File(prefsdir, currBean+".xml");
          File jarFile = pluginfiles[i];
          Object plugin;

          try {
              FileInputStream inStream = new FileInputStream(serializedFile);
              XMLDecoder d = new XMLDecoder(new BufferedInputStream(inStream));
              System.out.println("Deserializing plugin "+currBean+" from "+serializedFile.getName());
              plugin = d.readObject();
              d.close();
          } catch (Exception e) {
              System.out.println("Instantiating plugin "+currBean+" from "+pluginfiles[i].getName());
              plugin = Beans.instantiate(loader, currBean);
          }
          pluginList.addElement(plugin);
      }
      
      return pluginList;
  }
  
  public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
      Object o = actionEvent.getSource();
      loadSettingsPanel(buttonList.indexOf(o));
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane iconScrollPane;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel iconListPanel;
    private javax.swing.JPanel iconsPanel;
    // End of variables declaration//GEN-END:variables
  
}
