import java.util.*;
import java.sql.*;
//GUI Componenets
import javax.swing.*;
import javax.swing.table.*;

public class ProjectAddDialog extends javax.swing.JDialog {
  JDBCConnect dbConnection;
  
  public ProjectAddDialog(JFrame frame) {
    super(frame, true);
    dbConnection = new JDBCConnect();
    dbConnection.setParentFrame(frame);
    dbConnection.database = dbConnection.projectDatabase;
    dbConnection.table = dbConnection.projectTable;
    try {
      dbConnection.tableMap.init();
    } catch (java.sql.SQLException e) {
      System.err.println("Couldn't initialize table mapping");
    }
    initComponents();
    setLocationRelativeTo(frame);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    fieldScrollPane = new javax.swing.JScrollPane();
    fieldTable = new javax.swing.JTable();
    fieldPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });
    
    fieldTable.setModel(dbConnection.tableMap.toTableModel());
    fieldScrollPane.setViewportView(fieldTable);
    
    getContentPane().add(fieldScrollPane, java.awt.BorderLayout.CENTER);
    
    okButton.setText("OK");
    fieldPanel.add(okButton);
    
    cancelButton.setText("Cancel");
    fieldPanel.add(cancelButton);
    
    getContentPane().add(fieldPanel, java.awt.BorderLayout.SOUTH);
    
    pack();
  }//GEN-END:initComponents
    
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
      setVisible(false);
      dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane fieldScrollPane;
    private javax.swing.JTable fieldTable;
    private javax.swing.JPanel fieldPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables
    
}
