import java.net.*;
import java.io.*;
import javax.help.*;

public class HelpDisplay extends javax.swing.JFrame {
  private static String helpSetName = "csltcomm.hs";
  
  /** Creates new form HelpDisplay */
  public HelpDisplay() {
    try {
      String directory = System.getProperty("user.dir");
      String fileSeperator = System.getProperty("file.separator");
      URL helpFile = new URL("jar:file:"+directory+fileSeperator+"CsltComm.jar!/help/"+helpSetName);
      ClassLoader loader = this.getClass().getClassLoader();
      HelpSet set = new HelpSet(loader, helpFile);
      JHelp panel = new JHelp(set);
      this.getContentPane().add(panel);
    } catch(Exception e) {
      System.err.println("Couldn't print help: "+e);
    }
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
      exitForm();
    }//GEN-LAST:event_exitForm
    
    /** Exit the Application */
    private void exitForm() {
      setVisible(false);
      dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
