/**
 *
 * @author  jellis
 */

import java.beans.*;
import java.io.*;
import javax.swing.*;

public class SysTrayCustomizer extends javax.swing.JPanel implements java.beans.Customizer{
    
    private SysTray sysTray;
    
    /** Creates new customizer TimeOutCustomizer */
    public SysTrayCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        selectButtonGroup = new javax.swing.ButtonGroup();
        tabbedPane = new javax.swing.JTabbedPane();
        optionPanel = new javax.swing.JPanel();
        optionInputPanel = new javax.swing.JPanel();
        textLabel = new javax.swing.JLabel();
        optionButtonPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setMinimumSize(new java.awt.Dimension(238, 221));
        setPreferredSize(new java.awt.Dimension(387, 254));
        tabbedPane.setMinimumSize(new java.awt.Dimension(238, 221));
        tabbedPane.setPreferredSize(new java.awt.Dimension(387, 254));
        optionPanel.setLayout(new java.awt.BorderLayout());

        optionInputPanel.setLayout(new java.awt.GridBagLayout());

        textLabel.setText("No options present.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        optionInputPanel.add(textLabel, gridBagConstraints);

        optionPanel.add(optionInputPanel, java.awt.BorderLayout.CENTER);

        optionPanel.add(optionButtonPanel, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Options", optionPanel);

        add(tabbedPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void enableAll(boolean enable){
        if(! enable){
        } else {
        }
    }
    
    public void setObject(Object obj) {
    }    
    
    private void saveSysTraySettings() {
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel optionButtonPanel;
    private javax.swing.JPanel optionInputPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.ButtonGroup selectButtonGroup;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
    
}
