/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClntComm */

#ifndef _Included_ClntComm
#define _Included_ClntComm
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef ClntComm_TOP_ALIGNMENT
#define ClntComm_TOP_ALIGNMENT 0.0f
#undef ClntComm_CENTER_ALIGNMENT
#define ClntComm_CENTER_ALIGNMENT 0.5f
#undef ClntComm_BOTTOM_ALIGNMENT
#define ClntComm_BOTTOM_ALIGNMENT 1.0f
#undef ClntComm_LEFT_ALIGNMENT
#define ClntComm_LEFT_ALIGNMENT 0.0f
#undef ClntComm_RIGHT_ALIGNMENT
#define ClntComm_RIGHT_ALIGNMENT 1.0f
#undef ClntComm_serialVersionUID
#define ClntComm_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
#undef ClntComm_serialVersionUID
#define ClntComm_serialVersionUID 4613797578919906343LL
/* Inaccessible static: dbg */
/* Inaccessible static: class_00024java_00024awt_00024Container */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ContainerListener */
/* Inaccessible static: readObjectCallbacks */
#undef ClntComm_WHEN_FOCUSED
#define ClntComm_WHEN_FOCUSED 0L
#undef ClntComm_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define ClntComm_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef ClntComm_WHEN_IN_FOCUSED_WINDOW
#define ClntComm_WHEN_IN_FOCUSED_WINDOW 2L
#undef ClntComm_UNDEFINED_CONDITION
#define ClntComm_UNDEFINED_CONDITION -1L
#undef ClntComm_REQUEST_FOCUS_DISABLED
#define ClntComm_REQUEST_FOCUS_DISABLED 0L
#undef ClntComm_IS_DOUBLE_BUFFERED
#define ClntComm_IS_DOUBLE_BUFFERED 1L
#undef ClntComm_ANCESTOR_USING_BUFFER
#define ClntComm_ANCESTOR_USING_BUFFER 2L
#undef ClntComm_IS_PAINTING_TILE
#define ClntComm_IS_PAINTING_TILE 3L
#undef ClntComm_HAS_FOCUS
#define ClntComm_HAS_FOCUS 4L
#undef ClntComm_IS_OPAQUE
#define ClntComm_IS_OPAQUE 5L
#undef ClntComm_KEY_EVENTS_ENABLED
#define ClntComm_KEY_EVENTS_ENABLED 6L
#undef ClntComm_FOCUS_INPUTMAP_CREATED
#define ClntComm_FOCUS_INPUTMAP_CREATED 7L
#undef ClntComm_ANCESTOR_INPUTMAP_CREATED
#define ClntComm_ANCESTOR_INPUTMAP_CREATED 8L
#undef ClntComm_WIF_INPUTMAP_CREATED
#define ClntComm_WIF_INPUTMAP_CREATED 9L
#undef ClntComm_ACTIONMAP_CREATED
#define ClntComm_ACTIONMAP_CREATED 10L
#undef ClntComm_CREATED_DOUBLE_BUFFER
#define ClntComm_CREATED_DOUBLE_BUFFER 11L
#undef ClntComm_IS_PRINTING
#define ClntComm_IS_PRINTING 12L
#undef ClntComm_IS_PRINTING_ALL
#define ClntComm_IS_PRINTING_ALL 13L
/* Inaccessible static: defaultLayout */
#undef ClntComm_SECONDS
#define ClntComm_SECONDS 0L
#undef ClntComm_MINUTES
#define ClntComm_MINUTES 1L
#undef ClntComm_SHOW_TOTAL
#define ClntComm_SHOW_TOTAL 0L
#undef ClntComm_SHOW_BILLABLE
#define ClntComm_SHOW_BILLABLE 1L
#undef ClntComm_SHOW_EXPORT
#define ClntComm_SHOW_EXPORT 2L
/* Inaccessible static: totalSeconds */
/* Inaccessible static: billableSeconds */
/* Inaccessible static: frame */
/*
 * Class:     ClntComm
 * Method:    getIdleTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ClntComm_getIdleTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
