/*
 * DefaultForm.java
 *
 * Created on November 14, 2006, 10:55 PM
 */

package net.consultcomm.tabletree.sample;

import net.consultcomm.tabletree.*;

/**
 *
 * @author  jellis
 */
public class SampleTableTree extends javax.swing.JFrame {
  
  /** Creates new form DefaultForm */
  public SampleTableTree () {
    initComponents ();
    
    TableTree tableTree = new TableTree (new SampleModel ());
    
    setDefaultCloseOperation (javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle ("JTable & JTree");
    scrollPane.setViewportView (tableTree);
    
    getContentPane ().add (scrollPane, java.awt.BorderLayout.CENTER);
    
    pack ();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        scrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTable & JTree");
        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
      java.awt.EventQueue.invokeLater (new Runnable () {
        public void run () {
          new SampleTableTree ().setVisible (true);
        }
      });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    
}
