/*
 * TimeOutCustomizer.java
 *
 * Created on December 5, 2002, 10:13 AM
 */

package TimeOutBean;

/**
 *
 * @author  jellis
 */
public class TimeOutCustomizer extends javax.swing.JPanel {
    
    /** Creates new customizer TimeOutCustomizer */
    public TimeOutCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
