/*
 * TimeOutCustomizer.java
 *
 * Created on December 5, 2002, 10:13 AM
 */

//package TimeOutBean;

/**
 *
 * @author  jellis
 */

import java.beans.*;
import java.io.*;
import javax.swing.*;

public class TimeOutCustomizer extends javax.swing.JPanel implements java.beans.Customizer{
    
    private TimeOut timeOut;
    private static final int defaultTime = 120;
    
    /** Creates new customizer TimeOutCustomizer */
    public TimeOutCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pauseLabel = new javax.swing.JLabel();
        secField = new JNumberField(10);
        secLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pauseButton = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        switchButton = new javax.swing.JRadioButton();
        projectCombo = new javax.swing.JComboBox();
        useCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        pauseLabel.setText("Perform action when idle for");
        jPanel4.add(pauseLabel);

        secField.setColumns(10);
        secField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secFieldActionPerformed(evt);
            }
        });

        jPanel4.add(secField);

        secLabel.setText("seconds");
        jPanel4.add(secLabel);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)), "Action"));
        pauseButton.setSelected(true);
        pauseButton.setText("Pause after idle");
        pauseButton.setToolTipText("<html>\n<body>\n<h3>Pauses timer if the system has been idle for the entered number of seconds.</h3>\n</body>\n<html>");
        buttonGroup1.add(pauseButton);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        jPanel5.add(pauseButton, gridBagConstraints);

        switchButton.setText("Switch to project     ");
        switchButton.setToolTipText("<html>\n<body>\n<h3>\nSwitches to selected project if the system has been idle for the given number of seconds\n</h3>\n</body>\n</html>\n");
        buttonGroup1.add(switchButton);
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        jPanel6.add(switchButton);

        projectCombo.setMaximumRowCount(50);
        projectCombo.setToolTipText("<html>\n<body>\n<h3>Select project to switch to</h3>\n</body>\n</html>");
        jPanel6.add(projectCombo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
        jPanel5.add(jPanel6, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        useCheckBox.setText(" Use plugin?");
        useCheckBox.setToolTipText("<html>\n<body>\n<h3>\nCheck if you want to use the Time Out plugin\n</h3>\n</body>\n</html>");
        useCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useCheckBoxActionPerformed(evt);
            }
        });

        jPanel2.add(useCheckBox, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jPanel1.add(saveButton);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Label.foreground"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time Out Plugin");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        add(jLabel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_switchButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void secFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secFieldActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_secFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveTimeOutSettings();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void useCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useCheckBoxActionPerformed
        enableAll(useCheckBox.isSelected());
    }//GEN-LAST:event_useCheckBoxActionPerformed

    private void enableAll(boolean enable){
        if(! enable){
            secField.setEnabled(false);
            secField.setText("");
            projectCombo.setEnabled(false);
            pauseButton.setEnabled(false);
            switchButton.setEnabled(false);
            pauseLabel.setEnabled(false);
            secLabel.setEnabled(false);
        }else{
            secField.setEnabled(true);
            projectCombo.setEnabled(true);
            pauseButton.setEnabled(true);
            switchButton.setEnabled(true);
            pauseLabel.setEnabled(true);
            secLabel.setEnabled(true);
        }
    }
    
    public void setObject(Object obj) {
        timeOut = (TimeOut)obj;
        displayBean();
    }    
    
    private void displayBean(){
        secField.setText("" + timeOut.getSeconds());
        useCheckBox.setSelected(timeOut.isUse());
        pauseButton.setSelected(timeOut.isPauseTimer());
        switchButton.setSelected(timeOut.isChangeProject());
        
        String[] names = timeOut.getProjectNames();
        for(int i = 0; i < names.length; i++){
            projectCombo.addItem(names[i]);
        }
        projectCombo.setSelectedItem(timeOut.getProject());
        
        enableAll(timeOut.isUse());
    }
    
    private void saveTimeOutSettings() {
        boolean selected = useCheckBox.isSelected();
        int secs = 0;
        try{
            secs = Integer.parseInt(secField.getText());
        }catch(NumberFormatException e){
            if(selected){
                    secs = defaultTime;
            }else{
                secs = 0;
            }
        }
        timeOut.setUse(selected);
        timeOut.setSeconds(secs);
        timeOut.setPauseTimer(pauseButton.isSelected());
        timeOut.setChangeProject(switchButton.isSelected());
        timeOut.setProject((String)projectCombo.getSelectedItem());
        secField.setText("" + secs);
        
        try {
            File prefsdir = new File(System.getProperty("user.home")+System.getProperty("file.separator")+"CsltComm");
            File prefsFile = new File(prefsdir, "TimeOut.xml");
            FileOutputStream outStream = new FileOutputStream(prefsFile);
            XMLEncoder e = new XMLEncoder(new BufferedOutputStream(outStream));
            e.writeObject(timeOut);
            e.close();
        } catch (Exception e) {
            System.err.println("Couldn't save JDBC Prefs");
            e.printStackTrace(System.out);
        }
        
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField secField;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pauseLabel;
    private javax.swing.JComboBox projectCombo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton pauseButton;
    private javax.swing.JRadioButton switchButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel secLabel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox useCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
